"""
@Author: li
@Email: lijianqiao2906@live.com
@FileName: skill_template.py
@DateTime: 2026-05-08 23:49:00
@Docs: 按 Hermes SKILL.md 风格渲染 SOP Markdown 候选
"""

from dataclasses import dataclass
from datetime import UTC, datetime


@dataclass
class SkillCandidate:
    """LLM 生成的 SOP 候选结构。"""

    name: str
    description: str
    category: str
    when_to_use: list[str]
    quick_ref: list[str]
    procedure: list[str]
    pitfalls: list[str]
    verification: list[str]


def render_skill_md(candidate: SkillCandidate, sample_count: int) -> str:
    """渲染 SOP Markdown。"""
    today = datetime.now(UTC).strftime("%Y-%m-%d")
    return f"""---
name: {candidate.name}
description: {candidate.description}
version: 0.1.0
author: aiops-bot
tags:
  - {candidate.category}
metadata:
  hermes:
    auto_generated: true
    generated_at: {today}
    sample_count: {sample_count}
---

## When to use

{_bullets(candidate.when_to_use)}

## Quick reference

{_bullets(candidate.quick_ref)}

## Procedure

{_numbered(candidate.procedure)}

## Pitfalls

{_bullets(candidate.pitfalls) if candidate.pitfalls else "_暂无已知坑点_"}

## Verification

{_bullets(candidate.verification)}

---

*This SOP was auto-generated by AIOps from {sample_count} historical successful cases.*
*Review before merging. Generated on {today}.*
"""


def _bullets(items: list[str]) -> str:
    """渲染无序列表。"""
    return "\n".join(f"- {item}" for item in items) if items else "_无_"


def _numbered(items: list[str]) -> str:
    """渲染有序列表。"""
    return "\n".join(f"{index + 1}. {item}" for index, item in enumerate(items)) if items else "_无_"
